version: "3"

services:
  app:
    # Esta linea buildea con una imagen ya creada.
    #image: platziapp
    
    # Esta linea buildea desde nuestro path .
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    # Depende de db service
    depends_on:
      - db
    #ports:
    #  - "3000-3003:3000"
    # Agradamos esta instruccion para compartir el codigo.
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: mongo

  lb:
    image: nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - app
    ports:
      - "80:80"